import './globals.css'
import NavBar from "@includes/NavBar"
import SideMenu from "@includes/SideMenu"
import Footer from '@includes/Footer'


export const metadata = {
  title: 'Oasis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className="flex grid-cols-2">
        <SideMenu />
        <main>
          <NavBar />
          {children}
          <Footer/>
        </main>
      </body>
    </html>

  )
}
